project:
  type: website

website:
  title: "EAHCP Science Committee"
  navbar:
    background: primary
    left:
      - text: "Program"
        href: "#program"
      - text: "Logistics"
        href: "#logistics"
      
format:
  html:
    theme: cosmo       # we can tweak this later
    toc: false
    page-layout: full
    smooth-scroll: true
    css: styles.css    # optional custom styling (below)
