project:
  type: website

website:
  title: "EAHCP Scientific Symposium"
  navbar:
    background: primary
    left:
      - text: "Program"
        href: "#program"
      - text: "Speakers & Abstracts"
        href: "#abstracts"
      - text: "Logistics"
        href: "#logistics"
      - text: "Parking"
        href: "#parking"
      - text: "Flyer"
        href: "#flyer"

format:
  html:
    theme: cosmo       # we can tweak this later
    toc: false
    page-layout: full
    smooth-scroll: true
    css: styles.css    # optional custom styling (below)
